---
- name: Install hyprland ecosystem
  pacman:
    state: present
    name:
      - hyprland
      - hyprlock
      - hypridle
      - hyprpaper
      - wofi
      - dolphin
      - kitty
      - uwsm
      - libnewt
      - noto-fonts
      - otf-font-awesome
      - waybar

- name: Enable waybar
  become: no
  ansible.builtin.systemd_service:
    name: waybar.service
    enabled: true
    scope: user


- name: Install AUR packages for hyprland
  become: no
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    aur_only: yes
    use: yay
    name:
      - waypaper
