---

- name: Configure All Machines
  hosts: all
  become: yes
  roles:
    - common

- name: Configure Laptops
  hosts: starlite
  become: yes
  roles:
    - starlite-mk-iv
    - hyprland
    - base-desktop
    - laptop

- name: Configure Desktop
  hosts: archdesktop
  become: yes
  roles:
    - hyprland
    - base-desktop
