---

- name: Configure All Machines
  hosts: all
  become: yes
  roles:
    - base-terminal

- name: Configure Laptops
  hosts: starlite
  become: yes
  roles:
    - starlite-mk-iv
    - hyprland
    - base-desktop


