---
- name: Install Arch on StarLabs Starlite MK IV
  hosts: localhost
  become: true
  roles:
    - role: docker
      vars:
        docker_users:
          - andrej
    - bluetooth
    - role: promtail
    - role: yubikey

  tasks:

    - name: Add pacman.conf
      ansible.builtin.copy:
        src: pacman.conf
        dest: /etc/pacman.conf
        owner: root
        group: root
        mode: '0644'

    - name: Install ansible and friends
      community.general.pacman:
        name:
          - ansible
          - yamllint
          - ansible-lint
          - molecule
          - molecule-docker

    - name: Install desktop applications
      community.general.pacman:
        state: present
        name:
          - firefox
          - bitwarden
          - obsidian
          - discord
          - gparted
          - syncthing
          - yubikey-manager
          - yubikey-manager-qt
          - shutter
          - gimp
          - thunderbird

    - name: Install flatpak apps
      community.general.flatpak:
        name:
          - io.bassi.Amberol
          - com.github.GradienceTeam.Gradience
          - io.posidon.Paper
        state: present

    - name: Install things
      community.general.pacman:
        name:
          - webp-pixbuf-loader  # webp thumbnails in gnome
          - power-profiles-daemon  # gnome power modes
          - screen
          - tilix
          - atuin

    # https://wiki.archlinux.org/title/Working_with_the_serial_console#Connect_using_a_terminal_emulator_program
    - name: Ensure to belong to uucp group for serial access
      ansible.builtin.user:
        name: andrej
        groups: uucp
        append: true
