---
- name: Install promtail
  pacman:
    name:
      - promtail

- name: Template
  template:
    src: promtail.yaml.j2
    dest: /etc/loki/promtail.yaml
  notify: Restart promtail

- name: Start and enable promtail
  ansible.builtin.systemd:
    name: promtail.service
    state: started
    enabled: yes