---
- name: Install promtail
  community.general.pacman:
    name:
      - promtail

- name: Template
  ansible.builtin.template:
    src: promtail.yaml.j2
    dest: /etc/loki/promtail.yaml
    mode: '0644'
  notify: Restart promtail

- name: Start and enable promtail
  ansible.builtin.systemd:
    name: promtail.service
    state: started
    enabled: yes
