---
- name: Install U2F pam module
  pacman:
    name:
      - pam-u2f
    state: present

- name: Create config dir
  command: mkdir -p ~/.config/Yubico
  become_user: andrej

- name: Create pam config
  shell: pamu2fcfg --verbose --origin=pam://{{ansible_nodename}} --appid=pam://{{ansible_nodename}} > ~/.config/Yubico/u2f_keys
  become_user: andrej

- name: Add yubikey sudo template
  template:
    src: etc/pam.d/sudo
    dest: /etc/pam.d/sudo

- name: Add yubikey gdm login template
  template:
    src: etc/pam.d/gdm-password
    dest: /etc/pam.d/gdm-password