---
- name: Install basic terminal packages
  pacman:
    state: present
    name:
      - less
      - nvim
      - openssh
      - zsh
      - ghostty
      - man
      - nerd-fonts
      - lazygit
      - curl
      - wget
      - ripgrep
      - fd
      - tailscale

- name: Configure passwordless sudo for ansible user
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/ansible-nopasswd
    line: 'andrej ALL=(ALL:ALL) NOPASSWD: ALL'
    state: present
    mode: '0440'
    create: yes
    validate: 'visudo -c -f %s'

- name: Create symlink for vim to nvim
  ansible.builtin.file:
    src: /usr/bin/nvim
    dest: /usr/bin/vim
    owner: root
    group: root
    state: link

- name: Create chezmoi.toml
  ansible.builtin.copy:
    src: chezmoi.toml
    dest: /home/andrej/.config/chezmoi/chezmoi.toml
    owner: andrej
    group: andrej
    mode: '644'

- name: Include yay installation for AUR packages
  ansible.builtin.import_tasks: yay.yml

- name: Create the `aur_builder` user
  become: yes
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    mode: 0644
    validate: 'visudo -cf %s'


- name: Include shell stuff
  ansible.builtin.import_tasks: zsh.yml
########################## snapper

- name: Install snapper stuff
  pacman:
    state: present
    name:
      - snap-pac
      - grub-btrfs
      # optionan but needed for grub-btrfs
      - inotify-tools

- name: Enable grub-btrfs
  ansible.builtin.systemd_service:
    name: grub-btrfsd
    state: started
    enabled: yes



- name: Include etckeeper
  ansible.builtin.import_tasks: etckeeper.yml
