---
- name: Install basic terminal packages
  pacman:
    state: present
    name:
      - less
      - nvim
      - openssh
      - zsh
      - ghostty

- name: Create symlink for vim to nvim
  ansible.builtin.file:
    src: /usr/bin/nvim
    dest: /usr/bin/vim
    owner: root
    group: root
    state: link

- name: Include yay installation for AUR packages
  ansible.builtin.import_tasks: yay.yml

- name: Setup my user
  ansible.builtin.user:
    name: andrej
    shell: /usr/bin/bash

- name: Create the `aur_builder` user
  become: yes
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    mode: 0644
    validate: 'visudo -cf %s'

- name: Install AUR packages
  become: no
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    aur_only: yes
    use: yay
    name:
      - bambustudio-bin
      - typora
      - libreoffice-fresh

